import 'package:flutter/material.dart';
import '../models/unit.dart';
import 'builders.dart';

/// Niveau A1 - Débutant complet : alphabet, salutations, nombres, famille,
/// nourriture, verbes au présent.
List<LearningUnit> buildA1Units() {
  return [
    LearningUnit(
      id: 'a1_u1',
      title: 'Alphabet et prononciation',
      description: 'Découvre les lettres cyrilliques et leurs sons',
      icon: Icons.abc,
      lessons: [
        lesson('a1_u1_l1', 'Les voyelles', [
          flashcard('a1_u1_l1_e1', 'а', 'a (comme dans "papa")', transliteration: 'a'),
          flashcard('a1_u1_l1_e2', 'о', 'o (comme dans "photo")', transliteration: 'o'),
          flashcard('a1_u1_l1_e3', 'у', 'ou (comme dans "loup")', transliteration: 'u'),
          mc('a1_u1_l1_e4', 'Quel son fait cette lettre ?', 'э', 'è', ['a', 'è', 'i', 'ou'], 'è'),
          mc('a1_u1_l1_e5', 'Quel son fait cette lettre ?', 'ы', 'y (son guttural unique au russe)', ['i', 'y (son guttural unique au russe)', 'a', 'ou'], 'y (son guttural unique au russe)'),
          listen('a1_u1_l1_e6', 'мама', 'maman', ['maman', 'papa', 'ami'], 'maman'),
          mc('a1_u1_l1_e7', 'Comment se lit "дом" ?', 'дом', 'maison', ['dom (maison)', 'mama (maman)', 'papa'], 'dom (maison)'),
        ]),
        lesson('a1_u1_l2', 'Les consonnes simples', [
          flashcard('a1_u1_l2_e1', 'м', 'm', transliteration: 'm'),
          flashcard('a1_u1_l2_e2', 'п / б', 'p / b', transliteration: 'p / b'),
          flashcard('a1_u1_l2_e3', 'т / д', 't / d', transliteration: 't / d'),
          flashcard('a1_u1_l2_e4', 'с / з', 's / z', transliteration: 's / z'),
          flashcard('a1_u1_l2_e5', 'к / г', 'k / g', transliteration: 'k / g'),
          mc('a1_u1_l2_e6', 'Que veut dire ce mot ?', 'папа', 'papa', ['maman', 'papa', 'ami'], 'papa'),
          listen('a1_u1_l2_e7', 'суп', 'soupe', ['soupe', 'lait', 'thé'], 'soupe'),
          translate('a1_u1_l2_e8', 'дом', 'maison', answerInRussian: false),
        ]),
        lesson('a1_u1_l3', 'Sons particuliers et premiers mots', [
          flashcard('a1_u1_l3_e1', 'ж', 'j (comme dans "jamais")', transliteration: 'j'),
          flashcard('a1_u1_l3_e2', 'ш', 'ch (comme dans "chat")', transliteration: 'ch'),
          flashcard('a1_u1_l3_e3', 'ч', 'tch (comme dans "tchèque")', transliteration: 'tch'),
          flashcard('a1_u1_l3_e4', 'я / ю / ё', 'ia / iou / io', transliteration: 'ia / iou / io'),
          flashcard('a1_u1_l3_e5', 'привет', 'salut', example: 'Привет!', exampleTranslation: 'Salut !'),
          mc('a1_u1_l3_e6', 'Que veut dire "спасибо" ?', 'спасибо', 'merci', ['merci', 'bonjour', 'oui'], 'merci'),
          listen('a1_u1_l3_e7', 'да', 'oui', ['oui', 'non', 'merci'], 'oui'),
          wordBank('a1_u1_l3_e8', 'Привет, мама!', 'Salut, maman !', ['мама!', 'Привет,'], ['Привет,', 'мама!']),
        ]),
      ],
    ),
    LearningUnit(
      id: 'a1_u2',
      title: 'Salutations et politesse',
      description: 'Dis bonjour, présente-toi et sois poli en russe',
      icon: Icons.waving_hand,
      lessons: [
        lesson('a1_u2_l1', 'Bonjour et au revoir', [
          flashcard('a1_u2_l1_e1', 'Привет', 'Salut', example: 'Привет! Как дела?', exampleTranslation: 'Salut ! Comment ça va ?'),
          flashcard('a1_u2_l1_e2', 'Здравствуйте', 'Bonjour (formel)', example: 'Здравствуйте, доктор.', exampleTranslation: 'Bonjour, docteur.'),
          flashcard('a1_u2_l1_e3', 'Пока', 'Salut / Au revoir (familier)'),
          flashcard('a1_u2_l1_e4', 'До свидания', 'Au revoir (formel)'),
          mc('a1_u2_l1_e5', 'Comment dit-on "bonjour" à son patron ?', 'Здравствуйте', 'Bonjour (formel)', ['Привет', 'Здравствуйте', 'Пока'], 'Здравствуйте'),
          listen('a1_u2_l1_e6', 'До свидания', 'Au revoir', ['Bonjour', 'Au revoir', 'Merci'], 'Au revoir'),
          translate('a1_u2_l1_e7', 'Пока', 'Salut', answerInRussian: false),
        ]),
        lesson('a1_u2_l2', "Souhaits selon l'heure", [
          flashcard('a1_u2_l2_e1', 'Доброе утро', 'Bonjour (le matin)'),
          flashcard('a1_u2_l2_e2', 'Добрый день', "Bonjour (l'après-midi)"),
          flashcard('a1_u2_l2_e3', 'Добрый вечер', 'Bonsoir'),
          flashcard('a1_u2_l2_e4', 'Спокойной ночи', 'Bonne nuit'),
          mc('a1_u2_l2_e5', "On dit ça à 9h du matin :", 'Доброе утро', 'Bonjour (le matin)', ['Добрый вечер', 'Доброе утро', 'Спокойной ночи'], 'Доброе утро'),
          listen('a1_u2_l2_e6', 'Спокойной ночи', 'Bonne nuit', ['Bonjour', 'Bonne nuit', 'Bon après-midi'], 'Bonne nuit'),
          wordBank('a1_u2_l2_e7', 'Добрый вечер, Анна!', 'Bonsoir, Anna !', ['Анна!', 'вечер,', 'Добрый'], ['Добрый', 'вечер,', 'Анна!']),
        ]),
        lesson('a1_u2_l3', 'Se présenter', [
          flashcard('a1_u2_l3_e1', 'Меня зовут...', "Je m'appelle...", example: 'Меня зовут Мария.', exampleTranslation: "Je m'appelle Maria."),
          flashcard('a1_u2_l3_e2', 'Как тебя зовут?', "Comment tu t'appelles ?"),
          flashcard('a1_u2_l3_e3', 'Очень приятно', 'Enchanté(e)'),
          flashcard('a1_u2_l3_e4', 'Как дела?', 'Comment ça va ?'),
          flashcard('a1_u2_l3_e5', 'Хорошо, спасибо', 'Bien, merci'),
          mc('a1_u2_l3_e6', 'Réponse à "Как дела?" :', 'Хорошо, спасибо', 'Bien, merci', ['Хорошо, спасибо', 'Как тебя зовут', 'До свидания'], 'Хорошо, спасибо'),
          translate('a1_u2_l3_e7', 'Меня зовут Иван.', "Je m'appelle Ivan.", answerInRussian: false),
          speak('a1_u2_l3_e8', 'Меня зовут Анна. Очень приятно!', "Je m'appelle Anna. Enchantée !"),
        ]),
      ],
    ),
    LearningUnit(
      id: 'a1_u3',
      title: "Nombres et l'heure",
      description: 'Compte, donne un prix, dis l\'heure et le jour',
      icon: Icons.numbers,
      lessons: [
        lesson('a1_u3_l1', 'Les nombres de 0 à 10', [
          flashcard('a1_u3_l1_e1', 'один, два, три', 'un, deux, trois'),
          flashcard('a1_u3_l1_e2', 'четыре, пять', 'quatre, cinq'),
          flashcard('a1_u3_l1_e3', 'шесть, семь', 'six, sept'),
          flashcard('a1_u3_l1_e4', 'восемь, девять, десять', 'huit, neuf, dix'),
          mc('a1_u3_l1_e5', 'Que veut dire "пять" ?', 'пять', 'cinq', ['trois', 'cinq', 'sept'], 'cinq'),
          listen('a1_u3_l1_e6', 'девять', 'neuf', ['huit', 'neuf', 'dix'], 'neuf'),
          translate('a1_u3_l1_e7', 'три', 'trois', answerInRussian: false),
        ]),
        lesson('a1_u3_l2', 'Les dizaines jusqu\'à 100', [
          flashcard('a1_u3_l2_e1', 'одиннадцать, двенадцать', 'onze, douze'),
          flashcard('a1_u3_l2_e2', 'двадцать', 'vingt'),
          flashcard('a1_u3_l2_e3', 'тридцать, сорок', 'trente, quarante'),
          flashcard('a1_u3_l2_e4', 'пятьдесят, сто', 'cinquante, cent'),
          mc('a1_u3_l2_e5', 'Que veut dire "двадцать" ?', 'двадцать', 'vingt', ['douze', 'vingt', 'cent'], 'vingt'),
          listen('a1_u3_l2_e6', 'сто', 'cent', ['dix', 'cent', 'mille'], 'cent'),
          translate('a1_u3_l2_e7', 'сорок', 'quarante', answerInRussian: false),
        ]),
        lesson('a1_u3_l3', "L'heure et les jours", [
          flashcard('a1_u3_l3_e1', 'Который час?', "Quelle heure est-il ?"),
          flashcard('a1_u3_l3_e2', 'понедельник, вторник', 'lundi, mardi'),
          flashcard('a1_u3_l3_e3', 'среда, четверг, пятница', 'mercredi, jeudi, vendredi'),
          flashcard('a1_u3_l3_e4', 'суббота, воскресенье', 'samedi, dimanche'),
          mc('a1_u3_l3_e5', 'Que veut dire "пятница" ?', 'пятница', 'vendredi', ['mercredi', 'vendredi', 'dimanche'], 'vendredi'),
          listen('a1_u3_l3_e6', 'суббота', 'samedi', ['lundi', 'samedi', 'jeudi'], 'samedi'),
          wordBank('a1_u3_l3_e7', 'Сегодня среда.', "Aujourd'hui c'est mercredi.", ['среда.', 'Сегодня'], ['Сегодня', 'среда.']),
        ]),
      ],
    ),
    LearningUnit(
      id: 'a1_u4',
      title: 'Famille et pronoms',
      description: 'Parle de ta famille avec les pronoms et "это"',
      icon: Icons.family_restroom,
      lessons: [
        lesson('a1_u4_l1', 'Pronoms et "это"', [
          flashcard('a1_u4_l1_e1', 'я, ты', 'je, tu'),
          flashcard('a1_u4_l1_e2', 'он, она, оно', 'il, elle, il/elle (neutre)'),
          flashcard('a1_u4_l1_e3', 'мы, вы, они', 'nous, vous, ils/elles'),
          flashcard('a1_u4_l1_e4', 'Это', "C'est / Voici", example: 'Это мой дом.', exampleTranslation: "C'est ma maison."),
          mc('a1_u4_l1_e5', 'Кто это? → "___ моя сестра."', 'Она', 'Elle', ['Он', 'Она', 'Они'], 'Она'),
          listen('a1_u4_l1_e6', 'Это моя мама.', "C'est ma mère.", ["C'est ma mère.", "C'est mon père.", "C'est ma sœur."], "C'est ma mère."),
          translate('a1_u4_l1_e7', 'Это мой дом.', "C'est ma maison.", answerInRussian: false),
        ]),
        lesson('a1_u4_l2', 'La famille', [
          flashcard('a1_u4_l2_e1', 'мама, папа', 'maman, papa'),
          flashcard('a1_u4_l2_e2', 'брат, сестра', 'frère, sœur'),
          flashcard('a1_u4_l2_e3', 'сын, дочь', 'fils, fille'),
          flashcard('a1_u4_l2_e4', 'бабушка, дедушка', 'grand-mère, grand-père'),
          mc('a1_u4_l2_e5', 'Que veut dire "сестра" ?', 'сестра', 'sœur', ['frère', 'sœur', 'fils'], 'sœur'),
          listen('a1_u4_l2_e6', 'дедушка', 'grand-père', ['grand-mère', 'grand-père', 'père'], 'grand-père'),
          matchPairs('a1_u4_l2_e7', [
            const MapEntry('мама', 'maman'),
            const MapEntry('папа', 'papa'),
            const MapEntry('брат', 'frère'),
            const MapEntry('сестра', 'sœur'),
          ]),
        ]),
        lesson('a1_u4_l3', 'Le possessif et "у меня есть"', [
          flashcard('a1_u4_l3_e1', 'мой / моя / моё', 'mon / ma / mon (neutre)'),
          flashcard('a1_u4_l3_e2', 'твой / твоя / твоё', 'ton / ta / ton (neutre)'),
          flashcard('a1_u4_l3_e3', 'У меня есть...', "J'ai...", example: 'У меня есть брат.', exampleTranslation: "J'ai un frère."),
          flashcard('a1_u4_l3_e4', 'У тебя есть...?', 'As-tu...?'),
          mc('a1_u4_l3_e5', '"J\'ai une sœur" se dit :', 'У меня есть сестра.', "J'ai une sœur.", ['У меня есть сестра.', 'У тебя есть сестра.', 'Это моя сестра.'], 'У меня есть сестра.'),
          translate('a1_u4_l3_e6', 'У меня есть брат.', "J'ai un frère.", answerInRussian: false),
          wordBank('a1_u4_l3_e7', 'У меня есть сестра.', "J'ai une sœur.", ['есть', 'сестра.', 'У', 'меня'], ['У', 'меня', 'есть', 'сестра.']),
          speak('a1_u4_l3_e8', 'Это моя семья: мама, папа и сестра.', "C'est ma famille : maman, papa et une sœur."),
        ]),
      ],
    ),
    LearningUnit(
      id: 'a1_u5',
      title: 'Nourriture et boissons',
      description: 'Commande à manger et utilise le premier cas (accusatif)',
      icon: Icons.restaurant,
      lessons: [
        lesson('a1_u5_l1', 'Vocabulaire de la nourriture', [
          flashcard('a1_u5_l1_e1', 'хлеб, вода', 'pain, eau'),
          flashcard('a1_u5_l1_e2', 'чай, кофе', 'thé, café'),
          flashcard('a1_u5_l1_e3', 'молоко, сок', 'lait, jus'),
          flashcard('a1_u5_l1_e4', 'мясо, рыба', 'viande, poisson'),
          flashcard('a1_u5_l1_e5', 'фрукты, овощи', 'fruits, légumes'),
          mc('a1_u5_l1_e6', 'Que veut dire "вода" ?', 'вода', 'eau', ['thé', 'eau', 'lait'], 'eau'),
          listen('a1_u5_l1_e7', 'кофе', 'café', ['thé', 'café', 'jus'], 'café'),
          translate('a1_u5_l1_e8', 'хлеб', 'pain', answerInRussian: false),
        ]),
        lesson('a1_u5_l2', "Je veux, j'aime, je mange (accusatif)", [
          flashcard('a1_u5_l2_e1', 'Я хочу...', 'Je veux...', example: 'Я хочу чай.', exampleTranslation: 'Je veux du thé.'),
          flashcard('a1_u5_l2_e2', 'Я люблю...', "J'aime...", example: 'Я люблю кофе.', exampleTranslation: "J'aime le café."),
          flashcard('a1_u5_l2_e3', 'Я ем / Я пью', 'Je mange / Je bois'),
          mc('a1_u5_l2_e4', '"Je bois de l\'eau" se dit :', 'Я пью воду.', "Je bois de l'eau.", ['Я пью воду.', 'Я ем воду.', 'Я хочу вода.'], 'Я пью воду.'),
          listen('a1_u5_l2_e5', 'Я люблю рыбу.', "J'aime le poisson.", ["J'aime le poisson.", "Je veux du poisson.", "Je mange de la viande."], "J'aime le poisson."),
          translate('a1_u5_l2_e6', 'Я хочу суп.', 'Je veux de la soupe.', answerInRussian: false),
          wordBank('a1_u5_l2_e7', 'Я люблю чай.', "J'aime le thé.", ['чай.', 'Я', 'люблю'], ['Я', 'люблю', 'чай.']),
        ]),
        lesson('a1_u5_l3', 'Au café / restaurant', [
          flashcard('a1_u5_l3_e1', 'Что это?', 'Qu\'est-ce que c\'est ?'),
          flashcard('a1_u5_l3_e2', 'Дайте, пожалуйста...', 'Donnez-moi, s\'il vous plaît...'),
          flashcard('a1_u5_l3_e3', 'Счёт, пожалуйста', "L'addition, s'il vous plaît"),
          flashcard('a1_u5_l3_e4', 'Вкусно!', "C'est délicieux !"),
          mc('a1_u5_l3_e5', 'Pour demander l\'addition on dit :', 'Счёт, пожалуйста', "L'addition, s'il vous plaît", ['Что это?', 'Счёт, пожалуйста', 'Вкусно!'], 'Счёт, пожалуйста'),
          translate('a1_u5_l3_e6', 'Дайте, пожалуйста, чай.', 'Donnez-moi du thé, s\'il vous plaît.', answerInRussian: false),
          speak('a1_u5_l3_e7', 'Дайте, пожалуйста, кофе и хлеб.', "Donnez-moi un café et du pain, s'il vous plaît."),
        ]),
      ],
    ),
    LearningUnit(
      id: 'a1_u6',
      title: 'Vie quotidienne et verbes',
      description: 'Conjugue au présent et pose des questions',
      icon: Icons.wb_sunny,
      lessons: [
        lesson('a1_u6_l1', 'Verbes au présent (-ать)', [
          flashcard('a1_u6_l1_e1', 'читать', 'lire', example: 'Я читаю книгу.', exampleTranslation: 'Je lis un livre.'),
          flashcard('a1_u6_l1_e2', 'работать', 'travailler', example: 'Он работает.', exampleTranslation: 'Il travaille.'),
          flashcard('a1_u6_l1_e3', 'делать', 'faire', example: 'Что ты делаешь?', exampleTranslation: 'Que fais-tu ?'),
          mc('a1_u6_l1_e4', '"Je lis" se dit :', 'Я читаю.', 'Je lis.', ['Я читаю.', 'Я работаю.', 'Я делаю.'], 'Я читаю.'),
          listen('a1_u6_l1_e5', 'Он работает.', 'Il travaille.', ['Il lit.', 'Il travaille.', 'Il mange.'], 'Il travaille.'),
          translate('a1_u6_l1_e6', 'Я работаю.', 'Je travaille.', answerInRussian: false),
        ]),
        lesson('a1_u6_l2', 'Verbes au présent (-ить) et questions', [
          flashcard('a1_u6_l2_e1', 'говорить', 'parler', example: 'Я говорю по-русски.', exampleTranslation: 'Je parle russe.'),
          flashcard('a1_u6_l2_e2', 'любить', 'aimer'),
          flashcard('a1_u6_l2_e3', 'Что? Кто? Где?', 'Quoi ? Qui ? Où ?'),
          flashcard('a1_u6_l2_e4', 'Когда? Почему?', 'Quand ? Pourquoi ?'),
          mc('a1_u6_l2_e5', '"Où ?" se dit :', 'Где?', 'Où ?', ['Что?', 'Где?', 'Когда?'], 'Где?'),
          translate('a1_u6_l2_e6', 'Я говорю по-русски.', 'Je parle russe.', answerInRussian: false),
          wordBank('a1_u6_l2_e7', 'Где ты работаешь?', 'Où travailles-tu ?', ['работаешь?', 'ты', 'Где'], ['Где', 'ты', 'работаешь?']),
        ]),
        lesson('a1_u6_l3', 'Ma journée', [
          flashcard('a1_u6_l3_e1', 'Я встаю', 'Je me lève'),
          flashcard('a1_u6_l3_e2', 'утром, днём', 'le matin, l\'après-midi'),
          flashcard('a1_u6_l3_e3', 'вечером, ночью', 'le soir, la nuit'),
          flashcard('a1_u6_l3_e4', 'Я иду домой', 'Je rentre à la maison'),
          mc('a1_u6_l3_e5', '"Le matin" se dit :', 'утром', 'le matin', ['утром', 'вечером', 'ночью'], 'утром'),
          listen('a1_u6_l3_e6', 'Я отдыхаю вечером.', 'Je me repose le soir.', ['Je travaille le matin.', 'Je me repose le soir.', 'Je mange à midi.'], 'Je me repose le soir.'),
          translate('a1_u6_l3_e7', 'Утром я работаю.', 'Le matin, je travaille.', answerInRussian: false),
          speak('a1_u6_l3_e8', 'Утром я встаю, а вечером я отдыхаю.', 'Le matin je me lève, et le soir je me repose.'),
        ]),
      ],
    ),
  ];
}
